name: addictivelearning
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc: ^3.1.0
  equatable: ^0.2.4
  page_indicator: ^0.3.0
  dio: ^3.0.8
  uni_links: ^0.2.0
  url_launcher: ^5.4.2
  flutter_appavailability: ^0.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Open Sans
      fonts:
        - asset: fonts/opensans.ttf
          weight: 400
          style: normal
